### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "dave",
  "email": "dave@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "dave@test.com",
  "password": "password"
}

### Events index
GET http://localhost:3000/events.json

### Events show
GET http://localhost:3000/events/3.json

### Events create
POST http://localhost:3000/events.json
Content-Type: application/json

{
  "subject": "Testing",
  "description": "test something",
  "user_id": 1,
  "start_time": "2022-01-02 12:30:00",
  "end_time": "2022-01-02 13:00:00"
}

### Events destroy
DELETE http://localhost:3000/events/6.json